### ISSUE TITLE
Genius Invokation TCG data

### ISSUE THREAD

**Issue by JokelBaf** [wavyflow/hoyoapi#25]
Hello, can you please add method to retrieve genshin TCG data (https://bbs-api-os.hoyolab.com/game_record/genshin/api/gcg/basicInfo)?

**Comment by wavyflow** [comment]
It will be added soon, but as a note, the interface that will be created may not be exactly the same as the output provided.

**Comment by wavyflow** [comment]
Hi, TCG has been adden in new version, you can update npm dependency

[https://github.com/wavyflow/hoyoapi/releases/tag/v1.1.0](Changelog)

**Comment by JokelBaf** [comment]
Thank you!
